version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      command: "create_default_setup"
      args:
        USER_ID: ${USER_ID:?"Please run as follows 'USER_ID=$(id -u)'"}
        GROUP_ID: ${GROUP_ID:?"Please run as follows 'GROUP_ID=$(id -g)'"}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    environment:
      LOGGER_AGENT_ENABLED: "yes"
    networks:
      my-network:
    user: ${CURRENT_UID:?"Please run as follows 'CURRENT_UID=$(id -u):$(id -g) docker-compose up'"}
    volumes:
      - ./app:/usr/app

networks:
  my-network:
