name: generate-releases-content
on:
  push:
    branches:
      - feature/grab-release-content

jobs:
  build:
    name: GenerateReleasesContent
    runs-on: ubuntu-latest
    steps:
      - id: release
        run: |
          tags=$(curl https://api.github.com/repos/laravel/framework/tags | jq -rc '.')
          for row in $(echo "${tags}" | jq -r '.[] | @base64'); do
              _jq() {
               echo ${row} | base64 --decode | jq -r ${1}
              }
             echo $(_jq '.name')
          done