name: generate-releases-content
on:
  push:
    branches:
      - feature/grab-release-content

jobs:
  build:
    name: GenerateReleasesContent
    runs-on: ubuntu-latest
    steps:
      - id: release
        run: |
          echo 1
          curl https://api.github.com/repos/laravel/framework/tags | jq .