name: gh-on-issue

on:
  push:
    branches:
      - dev

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          extended: true

      - uses: actions/checkout@v2

      - name: Create content
        run : |
          pushd docs
            mkdir themes
            mkdir -p content/posts
            pushd themes
              git clone https://github.com/ronv/listed
            popd
            
            file="content/posts/${{ github.sha }}.md"
  
            touch $file
            echo "---" > $file
            echo "title: \"${{ github.sha }}\"" >> $file
            echo "date: 2021-11-14T22:40:38Z" >> $file
            echo "draft: false" >> $file
            echo "---" >> $file
            echo "" >> $file
            echo "${{ github.sha }}" >> $file
  
            hugo -D -b https://laraboot-io.github.io/laravel-images/ -t listed
          popd

      - name: Publish content
        uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-action
        with:
          commit_message: 'New content: ${{ github.sha }}'
          commit_options: '--allow-empty'
          repository: .
          status_options: '--untracked-files=no'
          file_pattern: 'content/**/*'
          push_options: '--force'
          skip_dirty_check: true
          skip_fetch: true
          disable_globbing: true

      - name: Update Gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/public