name: grab-release-content
on:
  push:
    branches:
      - feature/grab-release-content

jobs:
  build:
    name: ReadLatestLaravelRelease
    runs-on: ubuntu-latest
    steps:
      - id: keydb
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: laravel
          repo: framework
          excludes: prerelease, draft
      - id: echo
        run: |
          # https://api.github.com/repos/laravel/framework/tags
          echo ${{ steps.keydb.outputs.release }}
          # zipball_url: 
          # https://api.github.com/repos/laravel/framework/zipball/refs/tags/${{ steps.keydb.outputs.release }}